import type { Models } from 'node-appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types src/lib/types`.

export enum ItemsType {
    IMAGE = "image",
    VIDEO = "video"
}

export enum AccessLogsAccessType {
    FIRST_TIME = "first_time",
    REPEAT_VIEW = "repeat_view"
}

export type Items = Models.Row & {
    storageFileId: string;
    guildId: string;
    channelId: string;
    messageId: string | null;
    authorId: string;
    type: ItemsType;
    flags: string[] | null;
    hash: string;
    sizeBytes: number;
    accessLogs: AccessLogs[];
}

export type AccessLogs = Models.Row & {
    viewerId: string;
    guildId: string;
    channelId: string;
    accessType: AccessLogsAccessType;
    completedJob: CompletedJobs;
    item: Items;
}

export type CompletedJobs = Models.Row & {
    jobId: string;
    uploadItem: Items;
    accessLog: AccessLogs[];
}
