import type { Models } from 'node-appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types src/lib/types`.

export enum ItemsType {
    IMAGE = "image",
    VIDEO = "video"
}

export enum AccessLogsAccessType {
    FIRST_TIME = "first_time",
    REPEAT_VIEW = "repeat_view"
}

export type Items = Models.Row & {
    storageFileId: string;
    guildId: string;
    channelId: string;
    messageId: string;
    authorId: string;
    type: ItemsType;
    flags: string[] | null;
    hash: string;
    sizeBytes: number;
}

export type AccessLogs = Models.Row & {
    itemId: Items[];
    viewerId: string;
    guildId: string;
    channelId: string;
    jobId: string;
    accessType: AccessLogsAccessType;
}
